# Generated by Django 4.2.22 on 2025-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Tytuł")),
                ("director", models.CharField(max_length=120, verbose_name="Reżyser")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Ocena"
                    ),
                ),
            ],
            options={
                "ordering": ["-rating", "title"],
            },
        ),
    ]
